### ISSUE TITLE
Liferay permissions performance bottleneck

### ISSUE THREAD

**Issue by kcramakrishna** [R-Knowsys/elasticray#14]
Results for search are taking too long to show up.

We explored this issue and found that Elasticsearch itself is returning the results fast and elasticray is giving them to Liferay but Liferay permission checking code is slowing up the process.

Liferay is retrieving the permission of each asset/document and matching it to the permissions of the logged in user. i.e. For *each* asset in the result set, it queries the DB again for its permissions and then matches it against the user. This is not a trivial problem but an abomination none the less and should have been solved earlier. Luckily elasticsearch is the best tool available to solve this problem.
 
http://stackoverflow.com/questions/10008427/liferay-search-and-security-model

https://issues.liferay.com/browse/LEP-3335

While this is not really a problem with elasticray, unless we handle this, elasticray will not have any utility. We have to try and compensate for Liferay limitation within elasticray.

Solution should be a 2 pronged approach: 
1. We will try and index user id permissions along with asset id in elasticsearch and retrieve only those results matching the permissions. This solves much of the problem.
2. To make it a complete solution, we will see if we can write a hook for Liferay to check permissions from elasticsearch index or ideally disable this function while using elasticray. 
Edit: Created a new task for this: https://github.com/R-Knowsys/elasticray/issues/16

We will also need to handle run time changes in asset and/or user permissions but 
a) re-indexing partially on the fly OR
b) invalidating partial index on the fly . This will force ES to re-index the changed user/asset/permission.

Other issues to be considered:
1. Inherited permissions for users and groups, 
2. Inherited permissions for assets - i.e. Directory level permissions.

**Comment by vijay-patil** [comment]
Added permission query to search query thereby improving the performance by leaps,
