### ISSUE TITLE
 search users using  search portlet It is displaying "SearchParseException & ClassCastException" in Elastic Search 1.4.0 version 

### ISSUE THREAD

**Issue by Haritha1** [R-Knowsys/elasticray#24]
Versions :: Liferay 6.2 CE GA2,Elastic Search 1.4.0,Elastic Ray v1.3.0.0 ,Jdk 1.5
Place Elastic Ray war file in liferay Deploy folder & Start liferay Application Server
Next, Go to Admin > Click on Control panel tab
Next ,Click on Server administration Link button in Control panel
Next ,Click on Execute button near 'Reindex all search indexes'
Next Create users and organization
Next ,search users & Organization in user and Organization page ,Here It is displaying Results see below screen 

![image](https://cloud.githubusercontent.com/assets/11157888/6891801/cc0b8816-d6db-11e4-8f28-19511e84299c.png)

Next Add Search Protlet by click on Add Button in Liferay welcome page

![image](https://cloud.githubusercontent.com/assets/11157888/6891852/1ecc9824-d6dc-11e4-98e9-7095ef1809a9.png)

While try to do user or organization  search using search portlet ,it is displaying "SearchParseException & ClassCastException" in Elastic Search 1.4.0  Console page

[2015-03-30 12:40:05,632][DEBUG][action.search.type ] [Astrid Bloom] [liferay][3], node[EZ4sfc8cT6yYm06QAU9-PQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@ffd379]
org.elasticsearch.search.SearchParseException: [liferay][3]: query[+(+companyId:10154 +((+entryClassName:com.liferay.portal.model.user +status:0) (+entryClassName:com.liferay.portlet.bookmarks.model.bookmarksentry +status:0) (+entryClassName:com.liferay.portlet.bookmarks.model.bookmarksfolder +status:0) (+entryClassName:com.liferay.portlet.blogs.model.blogsentry +status:0) (+entryClassName:com.liferay.portlet.documentlibrary.model.dlfileentry +status:0 +hidden:false) (+entryClassName:com.liferay.portlet.documentlibrary.model.dlfolder +status:0 +hidden:false) (+entryClassName:com.liferay.portlet.journal.model.journalarticle +status:0 +head:true) (+entryClassName:com.liferay.portlet.journal.model.journalfolder +status:0) (+entryClassName:com.liferay.portlet.messageboards.model.mbmessage +status:0 +discussion:false) (+entryClassName:com.liferay.portlet.wiki.model.wikipage +status:0))) +(assetCategoryTitles:versionassetCategoryTitles_en_US:version assetTagNames:version comments:version content:version description:version properties:version title:version url:version userName:version city:version country:version emailAddress:version firstName:version fullName:version lastName:version middleName:version region:version screenName:version street:version zip:version ddmContent:version extension:version fileEntryTypeId:version path:version classPK:version content_en_US:version description_en_US:version entryClassPK:version title_en_US:version type:version articleId:version)],from[0],size[25]: Parse Failure [Failed to parse source [{"from":0,"size":25,"query":{"query_string":{"query":"+(+(companyId:10154) +((+(entryClassName:com.liferay.portal.model.User) +(status:0)) (+(entryClassName:com.liferay.portlet.bookmarks.model.BookmarksEntry) +(status:0)) (+(entryClassName:com.liferay.portlet.bookmarks.model.BookmarksFolder) +(status:0)) (+(entryClassName:com.liferay.portlet.blogs.model.BlogsEntry) +(status:0)) (+(entryClassName:com.liferay.portlet.documentlibrary.model.DLFileEntry) +(status:0) +(hidden:false)) (+(entryClassName:com.liferay.portlet.documentlibrary.model.DLFolder) +(status:0) +(hidden:false)) (+(entryClassName:com.liferay.portlet.journal.model.JournalArticle) +(status:0) +(head:true)) (+(entryClassName:com.liferay.portlet.journal.model.JournalFolder) +(status:0)) (+(entryClassName:com.liferay.portlet.messageboards.model.MBMessage) +(status:0) +(discussion:false)) (+(entryClassName:com.liferay.portlet.wiki.model.WikiPage) +(status:0)))) +(assetCategoryTitles:versionassetCategoryTitles_en_US:version assetTagNames:version comments:version content:version description:version properties:version title:version url:version userName:version city:version country:version emailAddress:version firstName:version fullName:version lastName:version middleName:version region:version screenName:version street:version zip:version ddmContent:version extension:Version fileEntryTypeId:version path:version classPK:version content_en_US:version description_en_US:version entryClassPK:Version title_en_US:version type:Version articleId:version)"}},"sort":[{"_score":{}}],"facets":{"userId":{"terms":{"field":"userId","size":10}},"assetTagNames":{"terms":{"field":"assetTagNames","size":10}},"modified":{"range":{"field":"modified","ranges":[{"from":"20150330060000","to":"20150330080000"},{"from":"20150329070000","to":"20150330080000"},{"from":"20150323070000","to":"20150330080000"},{"from":"20150302070000","to":"20150330080000"},{"from":"20140330070000","to":"20150330080000"}]}},"assetCategoryIds":{"terms":{"field":"assetCategoryIds","size":10}},"entryClassName":{"terms":{"field":"entryClassName","size":10}},"folderId":{"terms":{"field":"folderId","size":10}},"groupId":{"terms":{"field":"groupId","size":10}}},"highlight":{"fields":{"content":{"fragment_size":80,"number_of_fragments":3},"title":{"fragment_size":80,"number_of_fragments":3},"content_en_US":{"fragment_size":80,"number_of_fragments":3},"title_en_US":{"fragment_size":80,"number_of_fragments":3}}}}]]
at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264)
at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
at org.elasticsearch.search.facet.range.RangeFacetParser.parse(RangeFacetParser.java:163)
at org.elasticsearch.search.facet.FacetParseElement.parse(FacetParseElement.java:93)
at org.elasticsearch.search.SearchService.parseSource(SearchService.java:665)
... 9 more

**Comment by vijay-patil** [comment]
the index name should be liferay_ for the template to work
